apiVersion: v1
stringData:
  POSTGRES_PASSWORD: 57VuhsKQVLraBuLws8QSxL1qFNnTwBA4zxqGP1umH98GNPWw8PS1QAuhZsAbsHRt
  DATABASE_URL: postgresql://bsbingo:57VuhsKQVLraBuLws8QSxL1qFNnTwBA4zxqGP1umH98GNPWw8PS1QAuhZsAbsHRt@postgres/bsbingo
  DJANGO_SECRET_KEY: 0GuSf1t0U4oKlfRspOPjxU91SyOknr1DJUAJzPAaYfdifVRjUaXpZbNImiPG7f0n
kind: Secret
metadata:
  name: secrets-config
type: Opaque
