apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bsbingo-prod

resources:
  - ../sandbox
  - secrets.yaml

patches:
- target:
    kind: SealedSecret
    name: secrets-config
  path: secrets.yaml
- patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: letsencrypt-prod
    - op: replace
      path: /spec/dnsNames
      value:
        - api.example.test
        - k8s.example.test
  target:
    kind: Certificate
    name: cluster-cert
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: replace
      path: /spec/routes/0/match
      value: Host(`api.example.test`)
  target:
    kind: IngressRoute
    name: backend-ingress
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: replace
      path: /spec/routes/0/match
      value: Host(`k8s.example.test`)
  target:
    kind: IngressRoute
    name: k8s-ingress
- patch: |-
    - op: replace
      path: /spec/backup/barmanObjectStore/destinationPath
      value: "s3://bsbingo-prod-backups/"
  target:
    kind: Cluster
    name: postgres


configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
     - ENVIRONMENT="production"
     - DJANGO_SETTINGS_MODULE="config.settings.production"
     - DJANGO_CSRF_TRUSTED_ORIGINS="https://example.test"
     - AWS_S3_CUSTOM_DOMAIN="example.test"

images:
  - name: 000000000000.dkr.ecr.eu-west-1.amazonaws.com/bsbingo-sandbox-backend
    newName: 000000000000.dkr.ecr.eu-west-1.amazonaws.com/bsbingo-backend
    newTag: latest

